/**
 * pnpm build:demo
 *
 * Generates demo/assets/data.js from the REAL artifacts: the fixture, the
 * signed package, the tampered copy, and the trusted verifier config. The
 * screens never hard-code a hash; every value on screen comes from here.
 * Also records the counts Malcolm narrates (tests, fields, contract tests)
 * by counting them, not typing them.
 */
import { copyFileSync, readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve } from "node:path";
import { build } from "esbuild";
import { nodeCryptoAdapter } from "../proof/src/verifier/adapters-node.js";
import { verifyPackage, type VerifierConfig } from "../proof/src/verifier/core.js";
import { formatReport } from "../proof/src/verifier/format.js";
import { BINDING_KEYS } from "../proof/src/binding.js";
import type { ReceiptPackage } from "../proof/src/receipt.js";

const ROOT = process.cwd();
const read = (p: string) => readFileSync(resolve(ROOT, p), "utf8");
const readJson = <T,>(p: string): T => JSON.parse(read(p)) as T;

function leafCount(value: unknown): number {
  if (typeof value === "object" && value !== null && !Array.isArray(value)) {
    return Object.values(value).reduce<number>((n, v) => n + leafCount(v), 0);
  }
  return 1;
}

function countMatches(dir: string, ext: string, re: RegExp): number {
  return readdirSync(resolve(ROOT, dir))
    .filter((f) => f.endsWith(ext))
    .reduce((n, f) => n + (read(`${dir}/${f}`).match(re) ?? []).length, 0);
}

async function main(): Promise<void> {
  const pkg = readJson<ReceiptPackage>("out/receipt.s2.package.json");
  const tampered = readJson<ReceiptPackage>("out/receipt.s2.tampered.json");
  const config = readJson<VerifierConfig>("proof/verifier.config.json");
  const mandate = readJson<Record<string, unknown>>("fixtures/s2/mandate.v3.json");
  const policy = readJson<Record<string, unknown>>("fixtures/s2/policy.v1.json");
  const request = readJson<Record<string, unknown>>("fixtures/s2/request.json");

  const genuine = await verifyPackage(pkg, config, nodeCryptoAdapter);
  const tamperedReport = await verifyPackage(tampered, config, nodeCryptoAdapter);

  const data = {
    generatedAt: new Date().toISOString(),
    company: "Onbehalf",
    tagline: "Agents act on behalf. We prove who.",
    /** No chain named: the demo submits no chain transaction (PBX-021). */
    environmentBadge: "Sandbox · Stripe test",
    story: {
      approver: "J. Tan",
      approverRef: pkg.receiptCore.approval.approverRef,
      requestedAt: request.requestedAt,
      expiresAt: "2026-09-18T21:15:01Z",
      /** Countdown shown on the queue and action detail, in seconds (14:32). */
      expiresInSeconds: 14 * 60 + 32,
    },
    core: pkg.receiptCore,
    proof: pkg.cryptographicProof,
    anchorProof: pkg.anchorProof,
    tampered: {
      core: tampered.receiptCore,
      proof: tampered.cryptographicProof,
      anchorProof: tampered.anchorProof,
    },
    mandate,
    policy,
    request,
    issuer: config.issuer,
    /** The trusted configuration the browser verifier checks against, same file as the CLI. */
    verifierConfig: config,
    bindingKeys: BINDING_KEYS,
    reports: { genuine, tampered: tamperedReport },
    cli: {
      genuine: { command: "pnpm verify out/receipt.s2.package.json", output: formatReport(genuine) },
      tampered: { command: "pnpm verify out/receipt.s2.tampered.json", output: formatReport(tamperedReport) },
    },
    counts: {
      proofTests: countMatches("proof/test", ".test.ts", /^\s*it\(/gm),
      signedFields: leafCount(pkg.receiptCore),
      contractTests: countMatches("contracts/test", ".t.sol", /function test/g),
      canonicalBytes: Buffer.byteLength(read("out/receipt.s2.canonical.json"), "utf8"),
    },
  };

  mkdirSync(resolve(ROOT, "demo/assets"), { recursive: true });
  const out = resolve(ROOT, "demo/assets/data.js");
  writeFileSync(out, `// Generated by \`pnpm build:demo\` from out/ and fixtures/. Do not edit.\nexport const DATA = ${JSON.stringify(data, null, 2)};\n`);
  console.log(`Wrote ${out}`);

  // The downloadable packages, served next to the pages.
  copyFileSync(resolve(ROOT, "out/receipt.s2.package.json"), resolve(ROOT, "demo/assets/receipt.s2.package.json"));
  copyFileSync(resolve(ROOT, "out/receipt.s2.tampered.json"), resolve(ROOT, "demo/assets/receipt.s2.tampered.json"));

  // The verifier core + WebCrypto adapter + canonicalize, bundled for the browser.
  const bundle = resolve(ROOT, "demo/assets/verifier.js");
  await build({
    entryPoints: [resolve(ROOT, "proof/src/verifier/browser-entry.ts")],
    bundle: true,
    format: "esm",
    target: "es2022",
    outfile: bundle,
    legalComments: "inline",
    banner: {
      js: "// Bundled by `pnpm build:demo` from proof/src/verifier (core + WebCrypto adapter)\n// and the canonicalize package (Apache-2.0). Same checks, same order, as the CLI.",
    },
  });
  console.log(`Wrote ${bundle}`);
  console.log(`counts: ${data.counts.proofTests} tests, ${data.counts.signedFields} signed fields, ${data.counts.contractTests} contract tests`);
  console.log(`genuine: ${genuine.result}  tampered: ${tamperedReport.result} (${tamperedReport.summary})`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
